# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CompanionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CompanionApp
  pod 'Alamofire', '~> 5.2'


  target 'CompanionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CompanionAppUITests' do
    # Pods for testing
  end

end
